"use client"

import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Wifi, WifiOff, XCircle, ArrowDown } from "lucide-react"
// import { JobStatusBadge } from "./job-status-badge"
import type { FineTuneJob, TrainingMetrics, SSEEvent } from "@/lib/finetune-types"